### ISSUE TITLE
Does not handle players with space in the name

### ISSUE THREAD

**Issue by Hawke** [jacquesh/getrankd#2]
getrankd errors if you try to add a match including a player with a space in the name.

**Comment by jacquesh** [comment]
Can you give steps to reproduce this? I started with a fresh match db and did the following:
- Add a game "mygame"
- Add a player "player1"
- Add a player "player 2"
- Add a match for mygame with player1 and player 2

It seemed to work just fine for me?

**Comment by Hawke** [comment]
Hmm, I created a player called “The Game” and added them to a match; it failed to load the site until I manually went in and renamed that player to “TheGame”.

**Comment by Hawke** [comment]
Hmm, I almost wonder — I may have merely not selected a game when hitting 'add match'. I have several players with spaces in the name now, and it doesn’t seem to have fazed the software. I’ll enter a new issue.
