### ISSUE TITLE
HTTP error 400 if no game selected

### ISSUE THREAD

**Issue by Hawke** [jacquesh/getrankd#6]
If you don’t select a game when adding a match, getrankd produces an HTTP 400 error. It should merely complain and allow you to try again.

**Comment by jacquesh** [comment]
After looking into #2 I added some very simple form validation. It should show an error if you try to submit without selecting a game and at least one player. Are you running on the latest commits to master (specifically 395af9b)?

**Comment by Hawke** [comment]
I am running the latest git version. Validation seems to be working just fine now!
